[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "supafunc"
version = "0.9.0"
dependencies = [
    "supabase_functions"
]

[tool.setuptools]
packages = ["supafunc",]